"""Dodanie kolumny status do Post

Revision ID: 26cc778a6e31
Revises: 87ba381fb631
Create Date: 2025-11-14 20:28:38.986345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cc778a6e31'
down_revision = '87ba381fb631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='oczekuje', nullable=False))

    # [ZMIANA] USUŃ LUB ZAKOMENTUJ PONIŻSZY BLOK 'with'
    # To on powoduje błąd. Twoja tabela 'slider_items' już jest poprawna.
    # with op.batch_alter_table('slider_items', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['slider_id', 'order_index'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # [ZMIANA] USUŃ LUB ZAKOMENTUJ PONIŻSZY BLOK 'with'
    # To jest ten sam błąd, tylko dla cofania migracji.
    # with op.batch_alter_table('slider_items', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###