"""Definitive fix for media_id and constraints

Revision ID: d2d972164c6c
Revises: 26cc778a6e31
Create Date: 2023-10-27 12:00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d972164c6c'
down_revision = '26cc778a6e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - CORRECTED ###
    
    # Ta część dotyczy tabeli 'slider_items' i jest OK
    with op.batch_alter_table('slider_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('caption', sa.String(length=255), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_slider_items_media_id_media'), 'media', ['media_id'], ['id'])
        batch_op.create_unique_constraint('uq_slider_order', ['slider_id', 'order_index'])

    # Ta część dotyczy tabeli 'sliders' i została RĘCZNIE NAPRAWIONA
    with op.batch_alter_table('sliders', schema=None) as batch_op:
        # POPRAWKA: Zastąpiono `None` prawidłową nazwą z Twojego modelu `app/models.py`
        batch_op.create_unique_constraint('uq_slider_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - CORRECTED ###
    with op.batch_alter_table('sliders', schema=None) as batch_op:
        # POPRAWKA: Zastąpiono `None` prawidłową nazwą
        batch_op.drop_constraint('uq_slider_name', type_='unique')

    with op.batch_alter_table('slider_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_slider_order', type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_slider_items_media_id_media'), type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('caption')
        batch_op.drop_column('media_id')

    # ### end Alembic commands ###